apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: skaffold-demo
build:
  artifacts:
  - image: vfarcic/devops-toolkit
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*
