apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
  - image: vfarcic/devops-toolkit
profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
        - k8s/*
  - name: prod
    deploy:
      kustomize:
        paths:
        - kustomize/overlays/production
